/* Configuration for clara generated by Alire */
#ifndef CLARA_CONFIG_H
#define CLARA_CONFIG_H

#define CRATE_VERSION "1.0.0"
#define CRATE_NAME "clara"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  1

#endif
